spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://localhost:5432/order_management
    username: dev
    password: 123dev123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    template:
      default-topic: order-events

grpc:
  client:
    user-service:
      address: discovery:///user-service
      negotiationType: plaintext
      enable-keepalive: true
    product-service:
      address: discovery:///product-service
      negotiationType: plaintext
      enable-keepalive: true
    inventory-service:
      address: discovery:///inventory-service
      negotiationType: plaintext
      enable-keepalive: true

app:
  kafka:
    order-topic: order-events