spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://localhost:5432/order_management
    username: dev
    password: 123dev123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

grpc:
  client:
    user-service:
      address: discovery:///user-service
      negotiationType: plaintext
      enable-keepalive: true
    product-service:
      address: discovery:///product-service
      negotiationType: plaintext
      enable-keepalive: true